In [2]:
import numpy as np

a=np.array([1,2,3])

a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
np.shape(a)

(3,)

In [5]:
2

2

In [25]:
b= np.array([[1, 2, 3],[4,5,6],[7,8,9]]) #crear una matriz

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
b.shape #cuantos renglones y columnas tiene una matriz

(3, 3)

In [11]:
c=np.zeros((2,3)) #para crear matriz con puros ceros
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
d=np.ones((4,2))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
f=np.full((5,2),7)  #5 renglones, 2 columnas y llena de 7
f

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [14]:
g=b[1:,1:]
g

array([[5, 6],
       [8, 9]])

In [16]:
g2=b[0:2, 0:2]
g2

array([[1, 2],
       [4, 5]])

In [17]:
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
g

array([[5, 6],
       [8, 9]])

In [20]:
g[1,1]=2021
g

array([[   5,    6],
       [   8, 2021]])

In [21]:
b

array([[   1,    2,    3],
       [   4,    5,    6],
       [   7,    8, 2021]])

In [27]:
b[1,1]=5050
b


array([[   1,    2,    3],
       [   4, 5050,    6],
       [   7,    8,    9]])